# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f90d1d658d77de8ecefb6740ec9e99eac14edade099b280ca07edb18803f6eb70c601aa575b33fbff3bf23743ca7fc3799561a92b83f1024113c1c96a1e203b

test:
  secret_key_base: 9d98ed87b541d2a0f1d2778c97274e81536b256e7c64f3205caaa65b74802d17bebffecfb6a19e5e726a2a7b5b125f08dfaf9d0b1655850c904386c325e8a2a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
